# Generated by Django 3.2.12 on 2024-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
