# Generated by Django 3.2.12 on 2024-05-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='module_id',
            new_name='module',
        ),
    ]
